// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    ping_pong
    (
        init => init
        ping => ping
        pong => pong
        didUserPing => did_user_ping
        getPongEnableTimestamp => get_pong_enable_timestamp
        getTimeToPong => get_time_to_pong
        getAcceptedPaymentToken => accepted_payment_token_id
        getPingAmount => ping_amount
        getDurationTimestamp => duration_in_seconds
        getUserPingTimestamp => user_ping_timestamp
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
